// <auto-generated />
using CSRO.Server.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSRO.Server.Api.MigrationsCustomer.SqlServerMigrations
{
    [DbContext(typeof(CustomersDbContext))]
    partial class CustomersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSRO.Server.Entities.Entity.ResourceSWI", b =>
                {
                    b.Property<string>("AtCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AtName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AtSwc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AzureResource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChatChannel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpEnvironment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubscriptionName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ResourceSWIs");
                });
#pragma warning restore 612, 618
        }
    }
}
