// <auto-generated />
using System;
using CSRO.Server.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSRO.Server.Entities.Migrations
{
    [DbContext(typeof(AppVersionContext))]
    partial class AppVersionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CSRO.Server.Entities.Entity.AppVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsFormat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecomendedAction")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionFull")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppVersions");

                    b.HasData(
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2020, 11, 22, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "<p>This is version 20</p>",
                            DetailsFormat = "html",
                            Link = "www.bing.com",
                            RecomendedAction = 1,
                            ReleasedAt = new DateTime(2020, 11, 22, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            VersionFull = "1.0.20.0",
                            VersionValue = 20
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2020, 11, 25, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "This is version 21, modified at 5:00 pm",
                            DetailsFormat = "text",
                            Link = "www.google.sk",
                            RecomendedAction = 2,
                            ReleasedAt = new DateTime(2020, 11, 25, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            VersionFull = "1.0.21.0",
                            VersionValue = 21
                        });
                });

            modelBuilder.Entity("CSRO.Server.Entities.Entity.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnBehalf")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestedFor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
